### ISSUE TITLE
FPS cut in half when connecting cables between NeoTech machines.

### ISSUE THREAD

**Issue by Amperthorpe** [modmuss50/Fluxed-Redstone#10]
Cables disconnected: http://i.imgur.com/P7dI9o4.png
Cables connected: http://i.imgur.com/Am5fAFb.png

I installed Fluxed Redstone because I'm not a fan of now NeoTech's cables work and I want cables with MCMultipart, but they are unusable when this happens.

**Comment by modmuss50** [comment]
Thanks for the report, I do plan on rewriting the power system to be more efficient. But I will take a look for you.
