### ISSUE TITLE
fluxedredstone{2.2.1.44} crashes dedicated Forge 1.10.2 build 2026 on startup

### ISSUE THREAD

**Issue by kreezxil** [modmuss50/Fluxed-Redstone#17]
Tesla updated to 1.10.2-1.2.1.41 and now your mod doesn't recognize it and complains that it can't find it.

crash report:
https://gist.github.com/35a896cbb831dd57b22c13efca1ca6fc

fml server latest:
https://gist.github.com/0b3d620b9cdc468a8d1b3d4ddd887598

**Comment by modmuss50** [comment]
Ok I have talked to the tesla dev and somethings have changed. This version of tesla is only an alpha so I will provide you with the jenkins link to a compatible version.

**Comment by modmuss50** [comment]
You can get a compatible version here: http://modmuss50.me:8080/job/FluxedRedstone/
