### ISSUE TITLE
Crash when using FR conduits with Mekanism

### ISSUE THREAD

**Issue by utoc** [modmuss50/Fluxed-Redstone#18]
Crash here: http://pastebin.com/rytkMjRY
and here: http://pastebin.com/aCpfKbfh

Running:

MCMultiPart-1.2.0-universal
FluxedRedstone-2.3.0.48
Tesla-1.10.2-1.2.1.42
RebornCore-1.10.2-2.6.2.15-universal
Mekanism-1.10.2-9.1.0.288

This has been tested with FML 2048 and 2011 for MC 1.10.2

The crash was caused by placing any of the FR conduits on a Mek power cube initially but now it seems ALL Mekanism items are effected.  For grins, I went back to a previous version of RebornCore/TechReborn (2.5.5.3/1.3.4.11 respectively) and experienced this crash still.

If, after reading the crash log, you think this is the fault of Mekanism, please let me know and I will submit this to @aidancbrady

EDIT: Updated report with new versions of FR/Tesla

**Comment by modmuss50** [comment]
Fixed
