### ISSUE TITLE
FR pipes completely ignore Mekanism Generators (and don't transfer power at all)

### ISSUE THREAD

**Issue by Shadows-of-Fire** [modmuss50/Fluxed-Redstone#19]
http://imgur.com/a/GCxv9
Not sure why they do this.  Latest versions of every mod involved (Mek, RF, ReCore, and Tesla) as of 10/10/2016.

They're completely fine with Mekanism Core machines, and EnderIO machines.

Actually, upon closer inspection, they refuse to transfer power at all.

Versions:  FluxedRedstone-2.5.0.51 ; EnderIO-3.0.1.120_beta ; RebornCore-2.7.3.46 ; Mekanism-9.2.0.292 ; Tesla-1.2.1.49

**Comment by modmuss50** [comment]
Huh, ok I will take a look.

**Comment by modmuss50** [comment]
I improved the handling of FE in the wires and now it should be a lot better.
