### ISSUE TITLE
chunk/dimension save/load

### ISSUE THREAD

**Issue by AngelCry** [modmuss50/Fluxed-Redstone#20]
hi. i looking for some help, if is possible. my problem is: wires tends to just disappear... today i decided to try this mod, because other mods i use do not provide any RF cables. so, i installed this mod, as well as reborn core, made few gold wires and used them to power up Refined Storage and few other machines. as power source i have small reactor from Extreme Reactors mod. everything been fine at this point. then i traveled to Nether, to collect some resources and when i back i found only few pieces of wire here and there, while rest are gone. i have no crash, so i have no some log. can you check if wires saved/loaded correctly when dimension loaded/unloaded? i dont know if this problem in this mod or come from some mod interaction, but will be thankfull for any help, because i dont know other mods which have only RF wires/cables.
about versions: MC 1.10.2, Forge 12.18.2.2106, Fluxed Redstone 2.5.0.51, RebornCore 2.7.0.31

**Comment by modmuss50** [comment]
It sounds like it could be another mod causing this issue, do wires from other mods disappear?

**Comment by AngelCry** [comment]
i thought i been clear enough about i do not have other wires and is why i tried this mod. well, actually Electric Advantage have some cable, but EA use is own power system and this cable can't transfer RF. and no, no other cables/pipes or any other blocks (there no big difference between most blocks, include cables, right? they are Blocks and some - TileEntities as well) gone from my current world so far. at same time, most blocks is just blocks, while your wires are MultiPart, so direct comparison won't be correct...
PS. there screenshot how is looks, just in case
![wires](https://i.imgur.com/pHGawQD.png)

**Comment by AngelCry** [comment]
uh. i dont know, why i not checked it before, but things even worse, than is looks. while there no visible wires and no way to target them, collisions still there. so, looks like is kind of render issue (and before you ask - no, i dont have OptiFine)

**Comment by modmuss50** [comment]
Humm, is the power being transfured? it might be that the client hasn't received the data from the server about the cables.

**Comment by AngelCry** [comment]
is single player game so i think there a little chance for client-server issues. about power - i need to think how to check it. i already removed visible pieces, so is somewhat hard connect something to something you can't even see

**Comment by AngelCry** [comment]
just checked - and yes, power transfered. so wires still here and function. you just can't see them and can't remove (because you can't target them. i mean - sometimes you can target some invisible blocks, but not in this case)

**Comment by modmuss50** [comment]
Humm, this is strange, I will take a look through the code when I get time.

**Comment by modmuss50** [comment]
I think it may have just been fixed on the main mcmp branch, I will try updating that at some point and see how it goes.

**Comment by AngelCry** [comment]
ah, so you think is bug mcmp. well, i see there version 1.3.0 released, so i going to check this soon as well. thanks for your time.

**Comment by modmuss50** [comment]
we use our own version of that now, so I will need to update our copy of it.

**Comment by modmuss50** [comment]
I assume this is a one off issue, so closing.
