### ISSUE TITLE
Power connection issues

### ISSUE THREAD

**Issue by xenoflot** [modmuss50/Fluxed-Redstone#23]
Howdy,

Discovered today that your cables _will_ connect
* IE capacitors
* Actually Additions machine (tested with energiser)
* AE2 (tested with Energy Acceptor and a growth accelerator)
* XU2 coal generator
* TechReborn coal generator
* NeoTech generator
* RFTools Shield Projector

 but will _not_ connect:

* RFTools powercells (tested with all cable variants)
* Woot (mob loot factory mod)

Cheers!

**Comment by xenoflot** [comment]
In the above post, I was just testing if they connected. Today I've been testing if they work.

Power source is a TechReborn coal gen.
Power consumers are an ActuallyAdditions Energiser and an IE LV capacitor. 
I'm using TheOneProbe to monitor the power levels.
Connecting using a Redstone Fluxed Wire

TOP reports the Energizer's power seems to be bouncing up and down.
The IE capacitor's value is increasing but in the negative direction!

In both cases, when connected with IE's LV wires, the energy flow is as expected.

Cheers!

ImmersiveEngineering 0.10-54
ActuallyAdditions 1.10.2-r97
TechReborn 1.10.2-1.4.16.133
FluxedRedstone 2.5.0.51

**Comment by modmuss50** [comment]
Should be a lot better in the next version.
