### ISSUE TITLE
Wires Connection Won't Work 1.11.2

### ISSUE THREAD

**Issue by ghost** [modmuss50/Fluxed-Redstone#24]
using 1.11.2 forge 13.20.0.2206 i used wires for use solar panel in techreborn mod and connect it to centrifuge in forestry. however, when i put ANY wire to the mfsu, solar panel or any energy generation product, the wire consumes ALL the energy, but not deliver it to the connected machine. it is very bad..

**Comment by ghost** [comment]
hey, new version isn't working. i tested with techreborn, i connected solar panel to MFE, solar panel has energy but fluxed redstone wire won't connect the energy to MFE. and i also tried with forestry.

**Comment by modmuss50** [comment]
Ok, I reopened the issue. I will take another look and see if I an figure out why.

**Comment by ghost** [comment]
thank you.

**Comment by modmuss50** [comment]
Seems to be an issue with TechReborn not pushing FE power correctly

**Comment by ghost** [comment]
hmm maybe, it effects the AA laser relays. therefore i could never connect any cable or energy thing from any other mod to TechReborn cable or machine. i couldn't get them work with TechReborn. last time a developer said "i need to make a special energy bla bla for reborncore". it's in [this link](https://minecraft.curseforge.com/projects/energy-converters?gameCategorySlug=mc-mods&projectID=254818#c17)

**Comment by modmuss50** [comment]
Yeah, could well be the same issue
