### ISSUE TITLE
FluxedRedstone Cables and Power Cells

### ISSUE THREAD

**Issue by MichaelRoesner** [modmuss50/Fluxed-Redstone#26]
Hey, I have a Power Cell hooked up to Solar Panels with FluxedRedstone Cables. The INPUT works just fine ( RF Gen -> Cable -> Cell ), but the Output doesnt work ( Power Cell -> Cable -> Farm ).

**Comment by modmuss50** [comment]
Should be fixed in the newest version, let me know if its not.
