### ISSUE TITLE
[1.10.2] Fluxed redstone Cabling Output power fluctuates

### ISSUE THREAD

**Issue by Morpheus1101** [modmuss50/Fluxed-Redstone#27]
My current setup is a Creative Power source from Draconic connected via any of the cables from FR to an Energy pylon from DE xfering power to a DE power storage and i noticed the power input fluctuates up and down an isnt constantly at the max rate of power output as apposed to other mod cabling.  is this a bug or intentional?

**Comment by modmuss50** [comment]
It might be improved in the newer version, let me know if its not.
