### ISSUE TITLE
Won't load with modpack

### ISSUE THREAD

**Issue by chrissquest** [modmuss50/Fluxed-Redstone#3]
Ok, found where the issues are =P

So i have a 1.8.9 modpack, and when i load it with redstone flux, it never gets past reloading model managers.

Log: http://pastebin.com/ZspYpcEb No crash report, it just freezes. Don't think there's much more to say

**Comment by modmuss50** [comment]
Could I have the full log? How many mods have you got, and what forge?

**Comment by chrissquest** [comment]
Ugg, I'm getting really really confused. But I think it works. I updated all my mods and forge, I'm getting other problems now, but I think it's because of a diff. mod. Ill tell you if anything goes wrong again.
