### ISSUE TITLE
[1.11.2] RFtools can't seem to push to Fluxed wires. Will still output to RFtools

### ISSUE THREAD

**Issue by Rosethorns** [modmuss50/Fluxed-Redstone#30]
Description:
It appears from some playing around that nothing in RFTools that outputs FU/RF will push to Fluxed wires.
Its too hard to tell whos side this is on so I'm posting it to both.

Recreate:
1. setup RFtools power provider
2. connect to provider using fluxed wire of any kind.
3. connect a power reciever.
4. no power will even enter the wire network
http://i.imgur.com/XIxfNHU.png

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2252
Fluxed Redstone: 2.6.0.54
RFTools: 2-0.011

Edit: It occurs to me I didn't clarify "Will still output to RFTools" Using a forestry engine as a power provider successfully pushed energy to the crafter in the linked picture.

**Comment by LocoMinerDad** [comment]
I have the same issue, Plus it is doing the same thing with future pack with its neon engine. I think it is this mod if its happening over multiple mods

**Comment by modmuss50** [comment]
Should work a lot better now. Sorry about being slow to fix.
