### ISSUE TITLE
[1.8.9] Bounding boxes and occasional non-rendering of cable

### ISSUE THREAD

**Issue by SwordKorn20** [modmuss50/Fluxed-Redstone#5]
Seems to be a bit of a problem with the bounding boxes. They only seem to update along one axis when connected to other cables.

Also sometimes placing a cable produces an invisible block with no bounding box or hit box. The block exists however, and has buggy collision with players. Noticed it in Creative when placing Enderium ones.

**Comment by SwordKorn20** [comment]
Also just noticed one of the bounding boxes failed to update and when I tried to break the cable, it crashed.

**Comment by modmuss50** [comment]
What version of forge are you using?

**Comment by SwordKorn20** [comment]
1.8.9-11.15.0.1708

**Comment by modmuss50** [comment]
I fixed the crash bug, forge _might_ be causing the issue, Im investigating anyway

**Comment by modmuss50** [comment]
I cannot repoduce
