### ISSUE TITLE
Wires voiding energy from things

### ISSUE THREAD

**Issue by BBoldt** [modmuss50/Fluxed-Redstone#7]
https://dl.dropboxusercontent.com/u/134976541/ShareX/2016-01/2016-01-24_16-46-43.mp4

Fluxed Redstone-1.0.1.9

The energy storage pictured is from neotech.

**Comment by BBoldt** [comment]
Same issue is not present when using BC energy pipes, so it must be fluxed redstone wires.

**Comment by modmuss50** [comment]
The power is being transferred into the wires, not a lot I can do without rewriting the powernet

**Comment by modmuss50** [comment]
One way to make the problem less ovious would be to reduce the amount of power each cable can store

**Comment by BBoldt** [comment]
It's not just being transferred, energy is getting voided. Wouldn't be an issue if the pipes only stored power, the issue is them losing it somewhere.

**Comment by modmuss50** [comment]
I've got an idea of where this might be coming from.

**Comment by modmuss50** [comment]
I think im going to rewrite the energy transfer code, it will be more fendily on the sevrer and fix issues like this.
