### ISSUE TITLE
Crash while loading in modpack.

### ISSUE THREAD

**Issue by chrissquest** [modmuss50/Fluxed-Redstone#9]
I'm getting a crash when I add this mod to my modpack. I updated most of my mods and forge.
Crash: http://pastebin.com/Er4f0TAW
My log is too big to paste :/  but I don't know if you really need it. I could give you a download If you really want.
I don't know what's causing it. It happens every time, any help?
EDIT: I have tested it more and it doesn't even work alone. Same crash with ItemMultipartPipe or something. I have Fluxed Redstone-1.2.0.24, mcjtylib-1.8.9-1.8.1beta6, MCMultiPart-1.0.5-universal, RebornCore-1.8.9-1.3.1.9-universal.

**Comment by ariosos** [comment]
Can confirm - was just getting the same error, too. I've attached my modlist. Using Forge 1.8.9-11.15.1.1741
(the FluxedRedstone - v1.2.0.24 - mod is in my "Crashables" folder, BTW - that's were I put mods that don't play nice!)
![fs_crash](https://cloud.githubusercontent.com/assets/7917753/13028229/00642e04-d237-11e5-8ede-11531b7d4fe2.jpg)

**Comment by chrissquest** [comment]
Ok, it was because I didn't update reborn core, I didn't realize there was a new version out =P

**Comment by modmuss50** [comment]
@ariosos is it working for you now? Make sure you update RebornCore

**Comment by drago15243** [comment]
Yes, it's working. Wish I could delete this issue =P Very simple mistake I made.

**Comment by ariosos** [comment]
Yes, it's working now.
